version: '3'

services:
  runner_monitor:
    build: .
    volumes:
      - .:/code
    command: python -u dumpmon.py
    network_mode: 'bridge'
    depends_on:
      - db
    links:
      - db
  db:
    image: 'mongo:latest'
    network_mode: 'bridge'
    volumes:
      - ./data:/data/db
    # doing umask since mongoDB writing to this volume will make the file become 600, which throws error when trying to re-run the containers
    command: \
      umask a=r+w+x; \ 
      mongod --port 27017
